### ISSUE TITLE
Forms buttons not working in uSync.Exporter 

### ISSUE THREAD

**Issue by dvdvliet** [KevinJump/uSync.Forms#1]
version: 8.0.0.0-rc1

Open uSync.Exporter, click on Forms button and I got this error:
![image](https://user-images.githubusercontent.com/11905479/124101784-fc9fa000-da5f-11eb-8fcb-3ea70c5fdb46.png)

installed usync package versions:
uSync 
v8.9.4 + Content Edition (v8.9.4), Snapshots (v8.10.1), Exporter (v8.10.1), PeopleEdition (v8.10.1), Publisher (v8.10.1), Complete (v8.10.1), FormsEdition (v8.0.0.0)

**Comment by KevinJump** [comment]
yeah at the moment the bug is the forms button shouldn't be there :( - we are working on the uSync.Complete bit for forms but its not quite there yet.

**Comment by ghost** [comment]
Looks like this issue can be closed since the button was removed in v9.0.1
https://github.com/KevinJump/uSync.Forms/releases/tag/v9.0.1
