### ISSUE TITLE
Export function not working

### ISSUE THREAD

**Issue by craigs100** [KevinJump/uSync.Forms#13]
uSync: v13.1.3 + FormsEdition (v13.0.0.0)
Umb: V13.2.2 + UForms v13.1.1 on Linux (local dev) and Windows shared hosting.

The site currently has 6 forms, 4 of which are under one folder. Also has 2 Prevalue sources set.

Doing a clean export from the main uSync Everything section only exports FormFolders. It is not exporting Forms, Prevalue sources or Data sources. 

Also a Clean Export doesn't appear to delete the FormFolders, Forms, and Prevalues folders before repopulating.

Doing an export from the uSync Forms section does the same.

It does save the files and prevalues etc. if each is manually saved, but not using the Export functions.

Please advise.

**Comment by KevinJump** [comment]
Hi, 

- Do you have any custom uSync config at all ? 
- Do you see the 'forms' box on the uSync dashboard ? 
 _(if you only have certain values in say `UiEnabledGroups` setting then it won't show or export the forms from the dashboard)_

- Is there anything in the logs

**Comment by craigs100** [comment]
Assumed just a standard uSync config as I haven't intervened with it.

The Forms section is in the dashboard, and when you operate either the main uSync Clean Export or the Forms section Export you see the boxes as shown below. In this instance there have been no changes but it always shows a "1" for the folder (which does exist).

![image](https://github.com/KevinJump/uSync.Forms/assets/1143883/1e22f65e-e10c-463b-bd7e-2c4645f79477)

Nothing untoward in the logs, just green info items: "uSync: Startup Complete 2ms"

If I delete the V9 folder and run the Forms Export, a new V9 folder is created with just a Form-Folders and uSync.config file. Forms, Prevalues and Data are ignored.

The config file contents being:-
```
﻿<?xml version="1.0" encoding="utf-8"?>
<uSync version="13.1.3.0" format="10.7.0" />
```

**Comment by craigs100** [comment]
When I import forms from an export where all the forms, prevals and datasources have been saved, to make uSync export them automatically, then there are typos in the response....
![Screenshot from 2024-04-18 23-52-56](https://github.com/KevinJump/uSync.Forms/assets/1143883/e0d9c2ed-c5e9-46b9-96e5-20e6998c3012)

**Comment by craigs100** [comment]
Have upgraded to Umb V3.3.0, UF V13.1.2, uSync v13.2.0 + FormsEdition (v13.0.0.0) still exactly the same. Only the Form-Folders folder is generated by either main uSync or forms exports. The other forms elements are only generated on save, which is a total PITA.

Site currently has 6 forms of an expected 13, so happy to help debug this, just don't know how. Let me know.

**Comment by craigs100** [comment]
Deleting the V9 folder and executing a Clean Export from the "Everything" section (the Forms section is next to it) results in this:-
![Screenshot from 2024-04-20 10-38-18](https://github.com/KevinJump/uSync.Forms/assets/1143883/452a2807-1b75-4c69-ba25-2127dc334ffe)
But there are 3 forms in the Forms root with one Folder containing 3 other forms, no Datasources and 2 Prevalue sources

Same result using the "Forms" section Export button, on local and live.

**Comment by craigs100** [comment]
Here's the appsettings.json snipped (this hasn't been touched)

```
{
    "uSync": {
        "Settings": {
            "RootFolder": "uSync/v9/",
            "Folders": [
                "uSync/Root/",
                "uSync/v9/"
            ],
            "IsRootSite": false,
            "LockRoot": true,
            "LockRootTypes": [],
            "DefaultSet": "Default",
            "ImportAtStartup": "None",
            "ExportAtStartup": "None",
            "ExportOnSave": "All",
            "UiEnabledGroups": "All",
            "ReportDebug": false,
            "AddOnPing": true,
            "RebuildCacheOnCompletion": false,
            "FailOnMissingParent": false,
            "FailOnDuplicates": false,
            "CacheFolderKeys": true,
            "ShowVersionCheckWarning": true,
            "CustomMappings": {},
            "SignalRRoot": "",
            "EnableHistory": true,
            "HistoryFolder": "",
            "DefaultExtension": "config",
            "ImportOnFirstBoot": false,
            "FirstBootGroup": "All",
            "DisableDashboard": false,
            "SummaryDashboard": false,
            "SummaryLimit": 1000,
            "HideAddOns": "licence",
            "DisableNotificationSuppression": false,
            "BackgroundNotifications": false
        },
        "Sets": {
            "Default": {
                "Enabled": true,
                "HandlerGroups": [],
                "DisabledHandlers": [],
                "HandlerDefaults": {
                    "Enabled": true,
                    "Actions": [],
                    "UseFlatStructure": true,
                    "GuidNames": false,
                    "FailOnMissingParent": false,
                    "Group": "",
                    "CreateClean": false,
                    "Settings": {}
                },
                "Handlers": {},
                "IsSelectable": false
            }
        }
    }
}
```

**Comment by KevinJump** [comment]
looks like its a breaking change from the core and the form handlers still use one of the older methods for exporting...

need to do some testing but this nightly build might solve it.

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync.Forms/overview/13.2.0-build.20240420.4

**Comment by craigs100** [comment]
Thanks for this. It worked great locally, but pushing it live via GitHub Actions failed. The error was:-

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I'm def not using Node to do anything, that I'm aware of at least. Have never seen a build fail before. This is the 77th push on this repo.  Could it be something in the nightly build? 

Anyway, FTPing the changes up has them working fine. So thanks for that, big relief :)

**Comment by KevinJump** [comment]
😞  - there is no node stuff in the package . (there is only a few lines of code in the change)..

Do you have a reference to the nightly repo in your actions (or do you have the nuget.config with an addtional line in it for the nightly feed ?

**Comment by craigs100** [comment]
I just have this in my csproj:-

`<PackageReference Include="uSync.Forms" Version="13.2.0-build.20240420.4" />`

**Comment by KevinJump** [comment]
if you don't already have a nuget.config folder in the root of the solution  then adding the below should do it

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nightly" value="https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by craigs100** [comment]
Added a nuget.config file to the root with your code and that's fixed it! Thanks very much for your help :)
