### ISSUE TITLE
Transferring form with RTE thank you message, not retaining 'Format message in rich text' check state

### ISSUE THREAD

**Issue by tristan-moss-2024** [KevinJump/uSync.Forms#14]
**Describe the bug**
After creating a form with an Rich Text Editor thank you message and pushing it to the server, we see that the thank you message is reverted to textarea rather than the Rich Text Editor.

**To Reproduce**
1. Create an Umbraco form with a Rich Text Editor thank you message. 
2. Push to server.
3. Check the form on the destination server, we observe the message as textarea, not RTE.

**Expected behavior**
The form on the destination server shows Rich Text Editor with the checkbox 'Format message in rich text' checked.

**About your Site (please complete the following information):**
 - Umbraco Version: 13.4.0
 - uSync Version: 13.1.5
 - Browser : Chrome

**Comment by KevinJump** [comment]
Fixed in 13.4.0 

https://www.nuget.org/packages/uSync.Forms/13.4.0
