### ISSUE TITLE
Disable Handler for uSync.Forms

### ISSUE THREAD

**Issue by bogdanvista** [KevinJump/uSync.Forms#17]
Hello,

Is there any way to disable the handler for Forms from appsettings.json? 
We have some config to disable Content Handlers on servers (but they are enabled for development). 
We recently added the uSync.Forms package and noticed that even though the UI doesn't show the Forms on servers (using UIEnabledGroups) the import runs when triggered from an API call. 

Thanks.

**Comment by bogdanvista** [comment]
Actually, I looked a bit through the code and noticed that if I add
`"formsHandler",
"folderHander",
"formsPreValueHandler",
"formsDataSourceHandler"`

to the DisabledHandlers then it disappears. 

It seems a bit weird as the other handlers are PascalCase. 
Is this the right way to do it? 

(Also FormsFolderHand**l**er is "folderHander")

**Comment by KevinJump** [comment]
yeah - a bit of inconsitancy :( but chaning that would make it a breaking change, I will take a look in newer versions i am not sure why we care about case at all really.
