### ISSUE TITLE
FieldPreValueSource - issue importing custom PreValue Source

### ISSUE THREAD

**Issue by leekelleher** [KevinJump/uSync.Forms#2]
I have a custom PreValue Source, but when I come to import I get an error...

    Reporting error Could not find entity IPrevalueSourceEntity with id

I'm using uSync Core v8.10, with uSync Forms v8.0RC1.

In the "Forms-PreValues" folder, the XML stub does have the correct corresponding GUID value in `FieldPreValueSourceTypeId`. 

If you need example code, here's my (cut down) custom PreValue Source code...

    public class MyCustomPreValueSource : FieldPreValueSourceType
    {
        public MyCustomPreValueSource()
        {
            Id = new Guid("99C2C29F-163C-45E9-BA70-2F02040525B7");
            Name = "My custom values";
            Description = "Something, something, something dark side.";
        }

        public override List<PreValue> GetPreValues(Field field, Form form)
        {
            var items = new List<PreValue>();

            items.Add(new PreValue { Id = 1, Value = "One" });
            items.Add(new PreValue { Id = 2, Value = "Two" });

            return new List<PreValue>();
        }

        public override List<Exception> ValidateSettings() => new List<Exception>();
    }

I'm not sure whether it's a bug or something else? Let me know if you need any more info.

**Comment by leekelleher** [comment]
@KevinJump Ignore me. I've compiled the source locally and tried out the bleeding-edge code, and the PreValueSource is imported fine. Basically need an RC2 (or whatever) release, which I'm sure you've already planned out. 😀 I'll close this issue off.

**Comment by KevinJump** [comment]
hi, yeah - not quite there, this week we should have a new version ready.
