### ISSUE TITLE
Iconfiguration manager is not always available

### ISSUE THREAD

**Issue by bielu** [KevinJump/uSync.Forms#20]
Hey Kevin!
I found another annoying issue 😂 
So in FormPickerChecker we used IConfigurationManager, which apparently depends on hosting enviroment setup might or might not be available... 

So as alternative we can inject Iconfiguration, or use IOptions, let me know which option do you prefer and I will submit pr with it :)

**Comment by KevinJump** [comment]
yeah sure, i have no real idea why i did it that way, must have had flashbacks to Umbraco 8 😨 

for this IConfiguration is probibly simpler, we don't have an IOptions model (we could add one if you have the time - but its probibly not worth it just for a single thing 🤷 ).

**Comment by KevinJump** [comment]
Was fixed in v13.4.2 (but release notes for v13.4.4 - include it)
