### ISSUE TITLE
Syncing Conditional Workflows in Form is broken

### ISSUE THREAD

**Issue by TheFogOfWar1** [KevinJump/uSync.Forms#24]
We are experiencing an issue with the syncing of Forms with Workflows which have conditionals enabled. The conditions are not present in the receiving environment. 

To temporarily fix this issue we manually put the conditions back. However when adding new fields or doing other changes to the form in the sending environment, the conditions are overwritten. 

Used Versions: 
Umbraco: 13.5.2
Umbraco Forms: 13.2.5
uSync.Complete:  13.2.5
uSync.Forms: 13.3.0

**Comment by TheFogOfWar1** [comment]
@KevinJump @bielu Could you guys provide us with an update or do you need more information? We would like to provide an update to our client.

**Comment by bielu** [comment]
@TheFogOfWar1 hey I can have a look into it on weekend, btw I am not official maintainer in this repo, but Kevin is 😜

**Comment by TheFogOfWar1** [comment]
@bielu Hey, I was not completely aware of this :) Many thanks in advance.

**Comment by KevinJump** [comment]
Hi, sorry for the delay - Fixed in v13.4.4
