### ISSUE TITLE
autocompleteAttribute is not syncronized from form settings

### ISSUE THREAD

**Issue by nc-mosl** [KevinJump/uSync.Forms#8]
When setting the attribute for 'Autocomplete' for the entire form in the form settings (See below), the setting is not picked up by uSync. 
![image](https://user-images.githubusercontent.com/56822488/206672491-f30265a4-3b12-4647-b766-dcf3827bbca2.png)

I expect it to be part of the FormSerializer, similar to the 'MarkMandatoryFields' attribute from the form setting.  https://github.com/KevinJump/uSync.Forms/blob/v10/main/uSync.Forms/Serializers/FormSerializer.cs

**Comment by nc-mosl** [comment]
@KevinJump , not sure if tagging is the way to notify :-)

**Comment by KevinJump** [comment]
Fixed and in v10.0.1

https://www.nuget.org/packages/uSync.Forms/10.0.1

**Comment by nc-mosl** [comment]
Great - thanks!
